[tool.isort] # конфиг для настройки автоматической сортировки импортов

profile = "black" # стиль формата - в современном python часто используется black
line_length = 140 # длина строки импорта, после преодоления которой происходит перенос
multi_line_output = 3 # формат переноса импортов при длинных строках, 3 означает перенос начиная со следующей строки построчно
include_trailing_comma = true # добавление запятой после последнего элемента в строке импорта